### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by 9mm** [yorickpeterse/nvim-pqf#8]
This is a really awesome plugin, I have been searching for something just like this that doesnt introduce tons of QF features that break windows, hotkeys, blah blah blah.

Would you ever have any interest in make columns as an alternate style? Like this

https://user-images.githubusercontent.com/17562139/137736502-91d32251-96a2-4c3f-ba74-65cfd336473e.mp4

**Comment by yorickpeterse** [comment]
@9mm Your recording doesn't make it clear what exactly it is that you're asking for. Could you explain exactly what you're asking for? 

Generally speaking, changing the format is tricky and not something I'm interested in because:

1. The syntax definitions that are generated are done so with the current format in mind. Allowing for arbitrary formats likely requires a different and more complicated approach.
2. It requires extensive changes to the plugin structure to allow for customizing the output. This would probably result in a full rewrite.
3. The plugin does what I need it do, and I like to keep the scope to exactly that, instead of supporting various features I don't use myself.

**Comment by 9mm** [comment]
@ 3) that makes sense, I figured that might be the case but I thought I might ask anyway

**Comment by 9mm** [comment]
Oops hit enter too soon. I was just referring to columns here, so everything aligns. It appears you already partially supported columns, just in 2 groups instead of 3.=

<img width="436" alt="image" src="https://github.com/yorickpeterse/nvim-pqf/assets/1386207/5d1640db-fac8-45c2-9952-21554836b477">

**Comment by yorickpeterse** [comment]
@9mm The syntax definition expects that the location follows the format `file:line(:column)?`. In _theory_ alignment would be possible, but it would require dynamically adjusting the syntax definition to account for that. Injecting extra vertical separators would further complicate things.

All things considered, I don't feel this is worth the effort, so I'll close this issue.
